# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
#
# https://stackoverflow.com/questions/39728709/using-an-alternate-complier-for-travis-ci-r-project-builds

language: R
cache: packages
sudo: false
warnings_are_errors: true

os:
#  - linux
  - osx

r:
  - release
#  - devel
#  - oldrel

# Nicked from https://github.com/spatstat/spatstat/blob/master/.travis.yml
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  apt:
    packages:
    - tk-dev
    - bwidget
