# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
#
# https://stackoverflow.com/questions/39728709/using-an-alternate-complier-for-travis-ci-r-project-builds

language: R
cache: packages
services:
  - xvfb
warnings_are_errors: true

os:
#  - osx
  - linux
#before_install:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start

r:
  - release
  - devel
#  - oldrel

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0; fi
#- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi

# Nicked from https://github.com/spatstat/spatstat/blob/master/.travis.yml
addons:
  apt:
    packages:
    - tk-dev
    - bwidget
